# Generated by Django 4.1.7 on 2023-04-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='о команде')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='Время начала')),
                ('lead_time', models.IntegerField(verbose_name='Часов на выполение')),
                ('time_spent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Потраченное время')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='Время окончания')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks_db.developer', verbose_name='Разработчик')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='Время начала')),
                ('lead_time', models.IntegerField(verbose_name='Часов на выполение')),
                ('time_spent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Потраченное время')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='Время окончания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks_db.task', verbose_name='Задача')),
            ],
        ),
        migrations.CreateModel(
            name='ItProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Время начала')),
                ('deadline', models.DateField(verbose_name='Крайний срок')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks_db.developmentteam', verbose_name='Команда разработки')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks_db.itproject', verbose_name='ИТ проект')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks_db.developmentteam', verbose_name='Команда разработки'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('lead_time__gt', 0)), name='Часов на выполение задачи'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('time_spent__gte', 0)), name='Потраченное время на задачу'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gte', models.F('start_time'))), name='Время окончания задачи'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.CheckConstraint(check=models.Q(('lead_time__gt', 0)), name='Часов на выполение подзадачи'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.CheckConstraint(check=models.Q(('time_spent__gte', 0)), name='Потраченное время на подзадачу'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gte', models.F('start_time'))), name='Время окончания подзадачи'),
        ),
        migrations.AddConstraint(
            model_name='itproject',
            constraint=models.CheckConstraint(check=models.Q(('deadline__gte', models.F('start_date'))), name='Время окончания проекта'),
        ),
        migrations.AddConstraint(
            model_name='expenses',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='Цена больше нуля'),
        ),
        migrations.AddConstraint(
            model_name='developer',
            constraint=models.CheckConstraint(check=models.Q(('salary__gt', 0)), name='Зарплата больше нуля'),
        ),
    ]
